
# This file is automatically generated, you probably don't want to edit this

bivcatOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivcatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            obs = FALSE,
            exp = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            chiSq = FALSE,
            phiind = FALSE,
            phiSq = FALSE,
            contCoef = FALSE,
            craV = FALSE,
            chuprov = FALSE,
            sakoda = FALSE,
            Qyule = FALSE,
            Yyule = FALSE,
            Vyule = FALSE,
            lambdaGKab = FALSE,
            lambdaGKba = FALSE,
            lambdaGKsym = FALSE,
            tauGKab = FALSE,
            tauGKba = FALSE,
            tauGKsym = FALSE,
            theilab = FALSE,
            theilba = FALSE,
            theilsym = FALSE,
            barplot = FALSE,
            yaxis = "ycounts",
            yaxisPc = "total_pc",
            xaxis = "xrows",
            bartype = "dodge",
            mosaicplot = FALSE, ...) {

            super$initialize(
                package="saRa",
                name="bivcat",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=FALSE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..chiSq <- jmvcore::OptionBool$new(
                "chiSq",
                chiSq,
                default=FALSE)
            private$..phiind <- jmvcore::OptionBool$new(
                "phiind",
                phiind,
                default=FALSE)
            private$..phiSq <- jmvcore::OptionBool$new(
                "phiSq",
                phiSq,
                default=FALSE)
            private$..contCoef <- jmvcore::OptionBool$new(
                "contCoef",
                contCoef,
                default=FALSE)
            private$..craV <- jmvcore::OptionBool$new(
                "craV",
                craV,
                default=FALSE)
            private$..chuprov <- jmvcore::OptionBool$new(
                "chuprov",
                chuprov,
                default=FALSE)
            private$..sakoda <- jmvcore::OptionBool$new(
                "sakoda",
                sakoda,
                default=FALSE)
            private$..Qyule <- jmvcore::OptionBool$new(
                "Qyule",
                Qyule,
                default=FALSE)
            private$..Yyule <- jmvcore::OptionBool$new(
                "Yyule",
                Yyule,
                default=FALSE)
            private$..Vyule <- jmvcore::OptionBool$new(
                "Vyule",
                Vyule,
                default=FALSE)
            private$..lambdaGKab <- jmvcore::OptionBool$new(
                "lambdaGKab",
                lambdaGKab,
                default=FALSE)
            private$..lambdaGKba <- jmvcore::OptionBool$new(
                "lambdaGKba",
                lambdaGKba,
                default=FALSE)
            private$..lambdaGKsym <- jmvcore::OptionBool$new(
                "lambdaGKsym",
                lambdaGKsym,
                default=FALSE)
            private$..tauGKab <- jmvcore::OptionBool$new(
                "tauGKab",
                tauGKab,
                default=FALSE)
            private$..tauGKba <- jmvcore::OptionBool$new(
                "tauGKba",
                tauGKba,
                default=FALSE)
            private$..tauGKsym <- jmvcore::OptionBool$new(
                "tauGKsym",
                tauGKsym,
                default=FALSE)
            private$..theilab <- jmvcore::OptionBool$new(
                "theilab",
                theilab,
                default=FALSE)
            private$..theilba <- jmvcore::OptionBool$new(
                "theilba",
                theilba,
                default=FALSE)
            private$..theilsym <- jmvcore::OptionBool$new(
                "theilsym",
                theilsym,
                default=FALSE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "ycounts",
                    "ypc"),
                default="ycounts")
            private$..yaxisPc <- jmvcore::OptionList$new(
                "yaxisPc",
                yaxisPc,
                options=list(
                    "total_pc",
                    "column_pc",
                    "row_pc"),
                default="total_pc")
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xrows")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")
            private$..mosaicplot <- jmvcore::OptionBool$new(
                "mosaicplot",
                mosaicplot,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..chiSq)
            self$.addOption(private$..phiind)
            self$.addOption(private$..phiSq)
            self$.addOption(private$..contCoef)
            self$.addOption(private$..craV)
            self$.addOption(private$..chuprov)
            self$.addOption(private$..sakoda)
            self$.addOption(private$..Qyule)
            self$.addOption(private$..Yyule)
            self$.addOption(private$..Vyule)
            self$.addOption(private$..lambdaGKab)
            self$.addOption(private$..lambdaGKba)
            self$.addOption(private$..lambdaGKsym)
            self$.addOption(private$..tauGKab)
            self$.addOption(private$..tauGKba)
            self$.addOption(private$..tauGKsym)
            self$.addOption(private$..theilab)
            self$.addOption(private$..theilba)
            self$.addOption(private$..theilsym)
            self$.addOption(private$..barplot)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisPc)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
            self$.addOption(private$..mosaicplot)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        chiSq = function() private$..chiSq$value,
        phiind = function() private$..phiind$value,
        phiSq = function() private$..phiSq$value,
        contCoef = function() private$..contCoef$value,
        craV = function() private$..craV$value,
        chuprov = function() private$..chuprov$value,
        sakoda = function() private$..sakoda$value,
        Qyule = function() private$..Qyule$value,
        Yyule = function() private$..Yyule$value,
        Vyule = function() private$..Vyule$value,
        lambdaGKab = function() private$..lambdaGKab$value,
        lambdaGKba = function() private$..lambdaGKba$value,
        lambdaGKsym = function() private$..lambdaGKsym$value,
        tauGKab = function() private$..tauGKab$value,
        tauGKba = function() private$..tauGKba$value,
        tauGKsym = function() private$..tauGKsym$value,
        theilab = function() private$..theilab$value,
        theilba = function() private$..theilba$value,
        theilsym = function() private$..theilsym$value,
        barplot = function() private$..barplot$value,
        yaxis = function() private$..yaxis$value,
        yaxisPc = function() private$..yaxisPc$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value,
        mosaicplot = function() private$..mosaicplot$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..obs = NA,
        ..exp = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..chiSq = NA,
        ..phiind = NA,
        ..phiSq = NA,
        ..contCoef = NA,
        ..craV = NA,
        ..chuprov = NA,
        ..sakoda = NA,
        ..Qyule = NA,
        ..Yyule = NA,
        ..Vyule = NA,
        ..lambdaGKab = NA,
        ..lambdaGKba = NA,
        ..lambdaGKsym = NA,
        ..tauGKab = NA,
        ..tauGKba = NA,
        ..tauGKsym = NA,
        ..theilab = NA,
        ..theilba = NA,
        ..theilsym = NA,
        ..barplot = NA,
        ..yaxis = NA,
        ..yaxisPc = NA,
        ..xaxis = NA,
        ..bartype = NA,
        ..mosaicplot = NA)
)

bivcatResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivcatResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        asocind = function() private$.items[["asocind"]],
        errorind = function() private$.items[["errorind"]],
        barplot = function() private$.items[["barplot"]],
        mosaicplot = function() private$.items[["mosaicplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bivariate Data Analysis - Categorical")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Tables",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="asocind",
                title="Association Indices",
                visible="( chiSq || phiind || phisSq || contCoef || chuprov || sakoda || Qyule || Yyule || Vyule )",
                columns=list(
                    list(
                        `name`="t[chiSq]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C7\u00B2", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="v[chiSq]", 
                        `title`="Value", 
                        `visible`="(chiSq)"),
                    list(
                        `name`="t[phiind]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C6", 
                        `visible`="(phiind)"),
                    list(
                        `name`="v[phiind]", 
                        `title`="Value", 
                        `visible`="(phiind)"),
                    list(
                        `name`="t[phiSq]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C6\u00B2", 
                        `visible`="(phiSq)"),
                    list(
                        `name`="v[phiSq]", 
                        `title`="Value", 
                        `visible`="(phiSq)"),
                    list(
                        `name`="t[contCoef]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Contingency Index", 
                        `visible`="(contCoef)"),
                    list(
                        `name`="v[contCoef]", 
                        `title`="Value", 
                        `visible`="(contCoef)"),
                    list(
                        `name`="t[craV]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Cram\u00E9r's V", 
                        `visible`="(craV)"),
                    list(
                        `name`="v[craV]", 
                        `title`="Value", 
                        `visible`="(craV)"),
                    list(
                        `name`="t[chuprov]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Chuprov's Index", 
                        `visible`="(chuprov)"),
                    list(
                        `name`="v[chuprov]", 
                        `title`="Value", 
                        `visible`="(chuprov)"),
                    list(
                        `name`="t[sakoda]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Sakoda's Index", 
                        `visible`="(sakoda)"),
                    list(
                        `name`="v[sakoda]", 
                        `title`="Value", 
                        `visible`="(sakoda)"),
                    list(
                        `name`="t[Qyule]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Yule's Q Index", 
                        `visible`="(Qyule)"),
                    list(
                        `name`="v[Qyule]", 
                        `title`="Value", 
                        `visible`="(Qyule)"),
                    list(
                        `name`="t[Yyule]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Yule's Y Index", 
                        `visible`="(Yyule)"),
                    list(
                        `name`="v[Yyule]", 
                        `title`="Value", 
                        `visible`="(Yyule)"),
                    list(
                        `name`="t[Vyule]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Yule's V Index", 
                        `visible`="(Vyule)"),
                    list(
                        `name`="v[Vyule]", 
                        `title`="Value", 
                        `visible`="(Vyule)")),
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="errorind",
                title="Prediction Error Indices",
                visible="( lambdaGKab || lambdaGKba || lambdaGKsym)",
                columns=list(
                    list(
                        `name`="t[lambdaGKab]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03BB (rows)", 
                        `visible`="(lambdaGKab)"),
                    list(
                        `name`="v[lambdaGKab]", 
                        `title`="Value", 
                        `visible`="(lambdaGKab)"),
                    list(
                        `name`="t[lambdaGKba]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03BB (columns)", 
                        `visible`="(lambdaGKba)"),
                    list(
                        `name`="v[lambdaGKba]", 
                        `title`="Value", 
                        `visible`="(lambdaGKba)"),
                    list(
                        `name`="t[lambdaGKsym]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03BB (symmetric)", 
                        `visible`="(lambdaGKsym)"),
                    list(
                        `name`="v[lambdaGKsym]", 
                        `title`="Value", 
                        `visible`="(lambdaGKsym)"),
                    list(
                        `name`="t[tauGKab]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C4 (rows)", 
                        `visible`="(tauGKab)"),
                    list(
                        `name`="v[tauGKab]", 
                        `title`="Value", 
                        `visible`="(tauGKab)"),
                    list(
                        `name`="t[tauGKba]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C4 (columns)", 
                        `visible`="(tauGKba)"),
                    list(
                        `name`="v[tauGKba]", 
                        `title`="Value", 
                        `visible`="(tauGKba)"),
                    list(
                        `name`="t[tauGKsym]", 
                        `title`="", 
                        `type`="text", 
                        `content`="\u03C4 (symmetric)", 
                        `visible`="(tauGKsym)"),
                    list(
                        `name`="v[tauGKsym]", 
                        `title`="Value", 
                        `visible`="(tauGKsym)"),
                    list(
                        `name`="t[theilab]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Theil's U (rows)", 
                        `visible`="(theilab)"),
                    list(
                        `name`="v[theilab]", 
                        `title`="Value", 
                        `visible`="(theilab)"),
                    list(
                        `name`="t[theilba]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Theil's U (columns)", 
                        `visible`="(theilba)"),
                    list(
                        `name`="v[theilba]", 
                        `title`="Value", 
                        `visible`="(theilba)"),
                    list(
                        `name`="t[theilsym]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Theil's U (symmetric)", 
                        `visible`="(theilsym)"),
                    list(
                        `name`="v[theilsym]", 
                        `title`="Value", 
                        `visible`="(theilsym)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".barPlot",
                visible="(barplot)",
                requiresData=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="mosaicplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".mosaicPlot",
                visible="(mosaicplot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "yaxis",
                    "yaxisPc",
                    "xaxis",
                    "bartype")))}))

bivcatBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivcatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "bivcat",
                version = c(1,0,0),
                options = options,
                results = bivcatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Categorical Data
#'
#' 
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table (not
#'   necessary when providing a formula, see the examples)
#' @param cols the variable to use as the columns in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param chiSq \code{TRUE} or \code{FALSE} (default), provide Chi Squared
#' @param phiind \code{TRUE} or \code{FALSE} (default), provide Pearson's
#'   \u03c6
#' @param phiSq \code{TRUE} or \code{FALSE} (default), provide Pearson's
#'   \u03c6\u00B2
#' @param contCoef \code{TRUE} or \code{FALSE} (default), provide Pearson's
#'   contingency index
#' @param craV \code{TRUE} or \code{FALSE} (default), provide Cramér's V index
#' @param chuprov \code{TRUE} or \code{FALSE} (default), provide Chuprov's
#'   index
#' @param sakoda \code{TRUE} or \code{FALSE} (default), provide Sakoda's index
#' @param Qyule \code{TRUE} or \code{FALSE} (default), provide Yule's Q index
#'   for 2x2 contingency tables
#' @param Yyule \code{TRUE} or \code{FALSE} (default), provide Yule's Y index
#'   for 2x2 contingency tables
#' @param Vyule \code{TRUE} or \code{FALSE} (default), provide Yule's V index
#'   for 2x2 contingency tables
#' @param lambdaGKab \code{TRUE} or \code{FALSE} (default), provide Goodman
#'   and Kruskal lambda prediction error index (dependent variable by rows)
#' @param lambdaGKba \code{TRUE} or \code{FALSE} (default), provide Goodman
#'   and Kruskal lambda prediction error index (dependent variable by columns)
#' @param lambdaGKsym \code{TRUE} or \code{FALSE} (default), provide Goodman
#'   and Kruskal lambda prediction error index (symmetric)
#' @param tauGKab \code{TRUE} or \code{FALSE} (default), provide Goodman and
#'   Kruskal tau prediction error index (dependent variable by rows)
#' @param tauGKba \code{TRUE} or \code{FALSE} (default), provide Goodman and
#'   Kruskal tau prediction error index (dependent variable by columns)
#' @param tauGKsym \code{TRUE} or \code{FALSE} (default), provide Goodman and
#'   Kruskal tau prediction error index (symmetric)
#' @param theilab \code{TRUE} or \code{FALSE} (default), provide Theil's
#'   prediction error index (dependent variable by rows)
#' @param theilba \code{TRUE} or \code{FALSE} (default), provide Theil's
#'   prediction error index (dependent variable by columns)
#' @param theilsym \code{TRUE} or \code{FALSE} (default), provide Theil's tau
#'   prediction error index (symmetric)
#' @param barplot \code{TRUE} or \code{FALSE} (default), show barplots
#' @param yaxis ycounts (default) or ypc. Use respectively \code{counts} or
#'   \code{percentages} for the bar plot y-axis
#' @param yaxisPc total_pc (default), column_pc, or row_pc. Use respectively
#'   percentages \code{of total}, \code{within columns}, or \code{within rows}
#'   for the bar plot y-axis.
#' @param xaxis rows (default), or columns in bar plot X axis
#' @param bartype stack or side by side (default), barplot type
#' @param mosaicplot \code{TRUE} or \code{FALSE} (default), show mosaicplots
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$asocind} \tab \tab \tab \tab \tab A table of different bivariate association indicators \cr
#'   \code{results$errorind} \tab \tab \tab \tab \tab A table of different prediction error indicators \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mosaicplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
bivcat <- function(
    data,
    rows,
    cols,
    obs = FALSE,
    exp = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    chiSq = FALSE,
    phiind = FALSE,
    phiSq = FALSE,
    contCoef = FALSE,
    craV = FALSE,
    chuprov = FALSE,
    sakoda = FALSE,
    Qyule = FALSE,
    Yyule = FALSE,
    Vyule = FALSE,
    lambdaGKab = FALSE,
    lambdaGKba = FALSE,
    lambdaGKsym = FALSE,
    tauGKab = FALSE,
    tauGKba = FALSE,
    tauGKsym = FALSE,
    theilab = FALSE,
    theilba = FALSE,
    theilsym = FALSE,
    barplot = FALSE,
    yaxis = "ycounts",
    yaxisPc = "total_pc",
    xaxis = "xrows",
    bartype = "dodge",
    mosaicplot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bivcat requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- bivcatOptions$new(
        rows = rows,
        cols = cols,
        obs = obs,
        exp = exp,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        chiSq = chiSq,
        phiind = phiind,
        phiSq = phiSq,
        contCoef = contCoef,
        craV = craV,
        chuprov = chuprov,
        sakoda = sakoda,
        Qyule = Qyule,
        Yyule = Yyule,
        Vyule = Vyule,
        lambdaGKab = lambdaGKab,
        lambdaGKba = lambdaGKba,
        lambdaGKsym = lambdaGKsym,
        tauGKab = tauGKab,
        tauGKba = tauGKba,
        tauGKsym = tauGKsym,
        theilab = theilab,
        theilba = theilba,
        theilsym = theilsym,
        barplot = barplot,
        yaxis = yaxis,
        yaxisPc = yaxisPc,
        xaxis = xaxis,
        bartype = bartype,
        mosaicplot = mosaicplot)

    analysis <- bivcatClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

