
# This file is automatically generated, you probably don't want to edit this

bivmixOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivmixOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            groupBy = NULL,
            n = FALSE,
            missing = FALSE,
            mean = FALSE,
            median = FALSE,
            mode = FALSE,
            geommean = FALSE,
            trimean = FALSE,
            avquartile = FALSE,
            midrange = FALSE,
            trimmean = FALSE,
            Trim = 5,
            winsmean = FALSE,
            Win = 5,
            variance = FALSE,
            stddev = FALSE,
            geomsd = FALSE,
            meandev = FALSE,
            cv = FALSE,
            range = FALSE,
            iqr = FALSE,
            qd = FALSE,
            mad = FALSE,
            rcv = FALSE,
            irange = FALSE,
            NPerc = 90,
            min = FALSE,
            max = FALSE,
            q1 = FALSE,
            q2 = FALSE,
            q3 = FALSE,
            beta1 = FALSE,
            gamma1 = FALSE,
            h1 = FALSE,
            h3 = FALSE,
            beta2 = FALSE,
            gamma2 = FALSE,
            k2 = FALSE,
            k3 = FALSE,
            pc = FALSE,
            pcValues = "25,50,75",
            cohend = FALSE,
            rbp = FALSE,
            probsup = FALSE,
            etasq = FALSE,
            omegasq = FALSE,
            kwind = FALSE,
            hist = FALSE,
            dens = FALSE,
            norm = FALSE,
            box = FALSE,
            violin = FALSE,
            dot = FALSE,
            dotType = "jitter",
            boxMean = FALSE,
            innerf = 1.5,
            outerf = 3,
            qq = FALSE, ...) {

            super$initialize(
                package="saRa",
                name="bivmix",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..groupBy <- jmvcore::OptionVariable$new(
                "groupBy",
                groupBy,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..n <- jmvcore::OptionBool$new(
                "n",
                n,
                default=FALSE)
            private$..missing <- jmvcore::OptionBool$new(
                "missing",
                missing,
                default=FALSE)
            private$..mean <- jmvcore::OptionBool$new(
                "mean",
                mean,
                default=FALSE)
            private$..median <- jmvcore::OptionBool$new(
                "median",
                median,
                default=FALSE)
            private$..mode <- jmvcore::OptionBool$new(
                "mode",
                mode,
                default=FALSE)
            private$..geommean <- jmvcore::OptionBool$new(
                "geommean",
                geommean,
                default=FALSE)
            private$..trimean <- jmvcore::OptionBool$new(
                "trimean",
                trimean,
                default=FALSE)
            private$..avquartile <- jmvcore::OptionBool$new(
                "avquartile",
                avquartile,
                default=FALSE)
            private$..midrange <- jmvcore::OptionBool$new(
                "midrange",
                midrange,
                default=FALSE)
            private$..trimmean <- jmvcore::OptionBool$new(
                "trimmean",
                trimmean,
                default=FALSE)
            private$..Trim <- jmvcore::OptionNumber$new(
                "Trim",
                Trim,
                default=5)
            private$..winsmean <- jmvcore::OptionBool$new(
                "winsmean",
                winsmean,
                default=FALSE)
            private$..Win <- jmvcore::OptionNumber$new(
                "Win",
                Win,
                default=5)
            private$..variance <- jmvcore::OptionBool$new(
                "variance",
                variance,
                default=FALSE)
            private$..stddev <- jmvcore::OptionBool$new(
                "stddev",
                stddev,
                default=FALSE)
            private$..geomsd <- jmvcore::OptionBool$new(
                "geomsd",
                geomsd,
                default=FALSE)
            private$..meandev <- jmvcore::OptionBool$new(
                "meandev",
                meandev,
                default=FALSE)
            private$..cv <- jmvcore::OptionBool$new(
                "cv",
                cv,
                default=FALSE)
            private$..range <- jmvcore::OptionBool$new(
                "range",
                range,
                default=FALSE)
            private$..iqr <- jmvcore::OptionBool$new(
                "iqr",
                iqr,
                default=FALSE)
            private$..qd <- jmvcore::OptionBool$new(
                "qd",
                qd,
                default=FALSE)
            private$..mad <- jmvcore::OptionBool$new(
                "mad",
                mad,
                default=FALSE)
            private$..rcv <- jmvcore::OptionBool$new(
                "rcv",
                rcv,
                default=FALSE)
            private$..irange <- jmvcore::OptionBool$new(
                "irange",
                irange,
                default=FALSE)
            private$..NPerc <- jmvcore::OptionNumber$new(
                "NPerc",
                NPerc,
                default=90)
            private$..min <- jmvcore::OptionBool$new(
                "min",
                min,
                default=FALSE)
            private$..max <- jmvcore::OptionBool$new(
                "max",
                max,
                default=FALSE)
            private$..q1 <- jmvcore::OptionBool$new(
                "q1",
                q1,
                default=FALSE)
            private$..q2 <- jmvcore::OptionBool$new(
                "q2",
                q2,
                default=FALSE)
            private$..q3 <- jmvcore::OptionBool$new(
                "q3",
                q3,
                default=FALSE)
            private$..beta1 <- jmvcore::OptionBool$new(
                "beta1",
                beta1,
                default=FALSE)
            private$..gamma1 <- jmvcore::OptionBool$new(
                "gamma1",
                gamma1,
                default=FALSE)
            private$..h1 <- jmvcore::OptionBool$new(
                "h1",
                h1,
                default=FALSE)
            private$..h3 <- jmvcore::OptionBool$new(
                "h3",
                h3,
                default=FALSE)
            private$..beta2 <- jmvcore::OptionBool$new(
                "beta2",
                beta2,
                default=FALSE)
            private$..gamma2 <- jmvcore::OptionBool$new(
                "gamma2",
                gamma2,
                default=FALSE)
            private$..k2 <- jmvcore::OptionBool$new(
                "k2",
                k2,
                default=FALSE)
            private$..k3 <- jmvcore::OptionBool$new(
                "k3",
                k3,
                default=FALSE)
            private$..pc <- jmvcore::OptionBool$new(
                "pc",
                pc,
                default=FALSE)
            private$..pcValues <- jmvcore::OptionString$new(
                "pcValues",
                pcValues,
                default="25,50,75")
            private$..cohend <- jmvcore::OptionBool$new(
                "cohend",
                cohend,
                default=FALSE)
            private$..rbp <- jmvcore::OptionBool$new(
                "rbp",
                rbp,
                default=FALSE)
            private$..probsup <- jmvcore::OptionBool$new(
                "probsup",
                probsup,
                default=FALSE)
            private$..etasq <- jmvcore::OptionBool$new(
                "etasq",
                etasq,
                default=FALSE)
            private$..omegasq <- jmvcore::OptionBool$new(
                "omegasq",
                omegasq,
                default=FALSE)
            private$..kwind <- jmvcore::OptionBool$new(
                "kwind",
                kwind,
                default=FALSE)
            private$..hist <- jmvcore::OptionBool$new(
                "hist",
                hist,
                default=FALSE)
            private$..dens <- jmvcore::OptionBool$new(
                "dens",
                dens,
                default=FALSE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=FALSE)
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)
            private$..violin <- jmvcore::OptionBool$new(
                "violin",
                violin,
                default=FALSE)
            private$..dot <- jmvcore::OptionBool$new(
                "dot",
                dot,
                default=FALSE)
            private$..dotType <- jmvcore::OptionList$new(
                "dotType",
                dotType,
                options=list(
                    "jitter",
                    "stack"),
                default="jitter")
            private$..boxMean <- jmvcore::OptionBool$new(
                "boxMean",
                boxMean,
                default=FALSE)
            private$..innerf <- jmvcore::OptionNumber$new(
                "innerf",
                innerf,
                default=1.5)
            private$..outerf <- jmvcore::OptionNumber$new(
                "outerf",
                outerf,
                default=3)
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..groupBy)
            self$.addOption(private$..n)
            self$.addOption(private$..missing)
            self$.addOption(private$..mean)
            self$.addOption(private$..median)
            self$.addOption(private$..mode)
            self$.addOption(private$..geommean)
            self$.addOption(private$..trimean)
            self$.addOption(private$..avquartile)
            self$.addOption(private$..midrange)
            self$.addOption(private$..trimmean)
            self$.addOption(private$..Trim)
            self$.addOption(private$..winsmean)
            self$.addOption(private$..Win)
            self$.addOption(private$..variance)
            self$.addOption(private$..stddev)
            self$.addOption(private$..geomsd)
            self$.addOption(private$..meandev)
            self$.addOption(private$..cv)
            self$.addOption(private$..range)
            self$.addOption(private$..iqr)
            self$.addOption(private$..qd)
            self$.addOption(private$..mad)
            self$.addOption(private$..rcv)
            self$.addOption(private$..irange)
            self$.addOption(private$..NPerc)
            self$.addOption(private$..min)
            self$.addOption(private$..max)
            self$.addOption(private$..q1)
            self$.addOption(private$..q2)
            self$.addOption(private$..q3)
            self$.addOption(private$..beta1)
            self$.addOption(private$..gamma1)
            self$.addOption(private$..h1)
            self$.addOption(private$..h3)
            self$.addOption(private$..beta2)
            self$.addOption(private$..gamma2)
            self$.addOption(private$..k2)
            self$.addOption(private$..k3)
            self$.addOption(private$..pc)
            self$.addOption(private$..pcValues)
            self$.addOption(private$..cohend)
            self$.addOption(private$..rbp)
            self$.addOption(private$..probsup)
            self$.addOption(private$..etasq)
            self$.addOption(private$..omegasq)
            self$.addOption(private$..kwind)
            self$.addOption(private$..hist)
            self$.addOption(private$..dens)
            self$.addOption(private$..norm)
            self$.addOption(private$..box)
            self$.addOption(private$..violin)
            self$.addOption(private$..dot)
            self$.addOption(private$..dotType)
            self$.addOption(private$..boxMean)
            self$.addOption(private$..innerf)
            self$.addOption(private$..outerf)
            self$.addOption(private$..qq)
        }),
    active = list(
        vars = function() private$..vars$value,
        groupBy = function() private$..groupBy$value,
        n = function() private$..n$value,
        missing = function() private$..missing$value,
        mean = function() private$..mean$value,
        median = function() private$..median$value,
        mode = function() private$..mode$value,
        geommean = function() private$..geommean$value,
        trimean = function() private$..trimean$value,
        avquartile = function() private$..avquartile$value,
        midrange = function() private$..midrange$value,
        trimmean = function() private$..trimmean$value,
        Trim = function() private$..Trim$value,
        winsmean = function() private$..winsmean$value,
        Win = function() private$..Win$value,
        variance = function() private$..variance$value,
        stddev = function() private$..stddev$value,
        geomsd = function() private$..geomsd$value,
        meandev = function() private$..meandev$value,
        cv = function() private$..cv$value,
        range = function() private$..range$value,
        iqr = function() private$..iqr$value,
        qd = function() private$..qd$value,
        mad = function() private$..mad$value,
        rcv = function() private$..rcv$value,
        irange = function() private$..irange$value,
        NPerc = function() private$..NPerc$value,
        min = function() private$..min$value,
        max = function() private$..max$value,
        q1 = function() private$..q1$value,
        q2 = function() private$..q2$value,
        q3 = function() private$..q3$value,
        beta1 = function() private$..beta1$value,
        gamma1 = function() private$..gamma1$value,
        h1 = function() private$..h1$value,
        h3 = function() private$..h3$value,
        beta2 = function() private$..beta2$value,
        gamma2 = function() private$..gamma2$value,
        k2 = function() private$..k2$value,
        k3 = function() private$..k3$value,
        pc = function() private$..pc$value,
        pcValues = function() private$..pcValues$value,
        cohend = function() private$..cohend$value,
        rbp = function() private$..rbp$value,
        probsup = function() private$..probsup$value,
        etasq = function() private$..etasq$value,
        omegasq = function() private$..omegasq$value,
        kwind = function() private$..kwind$value,
        hist = function() private$..hist$value,
        dens = function() private$..dens$value,
        norm = function() private$..norm$value,
        box = function() private$..box$value,
        violin = function() private$..violin$value,
        dot = function() private$..dot$value,
        dotType = function() private$..dotType$value,
        boxMean = function() private$..boxMean$value,
        innerf = function() private$..innerf$value,
        outerf = function() private$..outerf$value,
        qq = function() private$..qq$value),
    private = list(
        ..vars = NA,
        ..groupBy = NA,
        ..n = NA,
        ..missing = NA,
        ..mean = NA,
        ..median = NA,
        ..mode = NA,
        ..geommean = NA,
        ..trimean = NA,
        ..avquartile = NA,
        ..midrange = NA,
        ..trimmean = NA,
        ..Trim = NA,
        ..winsmean = NA,
        ..Win = NA,
        ..variance = NA,
        ..stddev = NA,
        ..geomsd = NA,
        ..meandev = NA,
        ..cv = NA,
        ..range = NA,
        ..iqr = NA,
        ..qd = NA,
        ..mad = NA,
        ..rcv = NA,
        ..irange = NA,
        ..NPerc = NA,
        ..min = NA,
        ..max = NA,
        ..q1 = NA,
        ..q2 = NA,
        ..q3 = NA,
        ..beta1 = NA,
        ..gamma1 = NA,
        ..h1 = NA,
        ..h3 = NA,
        ..beta2 = NA,
        ..gamma2 = NA,
        ..k2 = NA,
        ..k3 = NA,
        ..pc = NA,
        ..pcValues = NA,
        ..cohend = NA,
        ..rbp = NA,
        ..probsup = NA,
        ..etasq = NA,
        ..omegasq = NA,
        ..kwind = NA,
        ..hist = NA,
        ..dens = NA,
        ..norm = NA,
        ..box = NA,
        ..violin = NA,
        ..dot = NA,
        ..dotType = NA,
        ..boxMean = NA,
        ..innerf = NA,
        ..outerf = NA,
        ..qq = NA)
)

bivmixResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivmixResults",
    inherit = jmvcore::Group,
    active = list(
        indicesnum = function() private$.items[["indicesnum"]],
        esindices = function() private$.items[["esindices"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bivariate Data Analysis - Mixed scales")
            self$add(jmvcore::Table$new(
                options=options,
                name="indicesnum",
                title="Statistics",
                visible="(n || missing || mean || median || mode || geommean || trimean || avquartile || midrange || trimmean || winsmean || variance || stddev || geomsd || meandev || cv || range || iqr || qd || mad || rcv || irange || min || max || q1 || q2 || q3 || pc || beta1 || gamma1 || h1 || h3 || beta2 || gamma2 || k2 || k3)",
                rows=1,
                clearWith=list(
                    "pcValues",
                    "NPerc",
                    "Trim",
                    "Win"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="esindices",
                title="Effect Size Indices",
                visible="(cohend ||  rbp || probsup || etasq || omegasq || kwind)",
                rows=1,
                columns=list()))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                clearWith=list(
                    "innerf",
                    "outerf"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="($key)")}))$new(options=options)))}))

bivmixBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bivmixBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "bivmix",
                version = c(0,1,0),
                options = options,
                results = bivmixResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Mixed Data
#'
#' 
#' @param data .
#' @param vars a vector of strings naming the variables of interest in
#'   \code{data}
#' @param groupBy a vector of strings naming the variables used to segment
#'   \code{vars}
#' @param n \code{TRUE} or \code{FALSE} (default), provides the N
#' @param missing \code{TRUE} or \code{FALSE} (default), provides the missing
#'   values
#' @param mean \code{TRUE} or \code{FALSE} (default), provides the mean
#' @param median \code{TRUE} or \code{FALSE} (default), provides the median
#' @param mode \code{TRUE} or \code{FALSE} (default), provides the mode
#' @param geommean \code{TRUE} or \code{FALSE} (default), provides the
#'   geometric mean
#' @param trimean \code{TRUE} or \code{FALSE} (default), provides the trimean
#' @param avquartile \code{TRUE} or \code{FALSE} (default), provides the
#'   quartiles average
#' @param midrange \code{TRUE} or \code{FALSE} (default), provides the
#'   mid-range
#' @param trimmean \code{TRUE} (default) or \code{FALSE}, provides the Trimmed
#'   Mean
#' @param Trim a number (detects by default the number) specifying the
#'   percentage of data to be trimmed
#' @param winsmean \code{TRUE} (default) or \code{FALSE}, provides the
#'   Winsorized Mean
#' @param Win a number (detects by default the number) specifying the
#'   percentage of data to be Winsorized
#' @param variance \code{TRUE} or \code{FALSE} (default), provides the
#'   variance
#' @param stddev \code{TRUE} or \code{FALSE} (default), provides the standard
#'   deviation
#' @param geomsd \code{TRUE} or \code{FALSE} (default), provides the geometric
#'   standard deviation
#' @param meandev \code{TRUE} or \code{FALSE} (default), provides the mean
#'   deviation
#' @param cv \code{TRUE} or \code{FALSE} (default), provides the cv
#' @param range \code{TRUE} or \code{FALSE} (default), provides the range
#' @param iqr \code{TRUE} or \code{FALSE} (default), provides the iqr
#' @param qd \code{TRUE} or \code{FALSE} (default), provides the quartile
#'   deviation
#' @param mad \code{TRUE} or \code{FALSE} (default), provides the mad
#' @param rcv \code{TRUE} or \code{FALSE} (default), provides the rcv
#' @param irange \code{TRUE} (default) or \code{FALSE}, provides the Inner
#'   Range
#' @param NPerc a number (detects by default the number) specifying the
#'   percentage of data used
#' @param min \code{TRUE} or \code{FALSE} (default), provides the minimum
#' @param max \code{TRUE} or \code{FALSE} (default), provides the maximum
#' @param q1 \code{TRUE} or \code{FALSE} (default), provides the first
#'   quartile
#' @param q2 \code{TRUE} or \code{FALSE} (default), provides the second
#'   quartile
#' @param q3 \code{TRUE} or \code{FALSE} (default), provides the third
#'   quartile
#' @param beta1 \code{TRUE} or \code{FALSE} (default), provide the Pearson's
#'   \u03B2\u2081 index
#' @param gamma1 \code{TRUE} or \code{FALSE} (default), provide the Fisher's
#'   \u03B3\u2081 index
#' @param h1 \code{TRUE} or \code{FALSE} (default), provide the H1 index
#' @param h3 \code{TRUE} or \code{FALSE} (default), provide the H3 index
#' @param beta2 \code{TRUE} or \code{FALSE} (default), provide the Pearson's
#'   \u03B2\u2082 index
#' @param gamma2 \code{TRUE} or \code{FALSE} (default), provide the Fisher's
#'   \u03B3\u2082 index
#' @param k2 \code{TRUE} or \code{FALSE} (default), provide the K2 index
#' @param k3 \code{TRUE} or \code{FALSE} (default), provide the K3 index
#' @param pc \code{TRUE} or \code{FALSE} (default), provides the Percentiles
#' @param pcValues a comma-separated list (default: 25,50,75) specifying the
#'   percentiles
#' @param cohend \code{TRUE} or \code{FALSE} (default), provides Cohen's d
#'   effect size indicator
#' @param rbp \code{TRUE} or \code{FALSE} (default), provides point-biserial
#'   correlation
#' @param probsup \code{TRUE} or \code{FALSE} (default), provides probability
#'   of superiority effect size indicator
#' @param etasq \code{TRUE} or \code{FALSE} (default), provides \u03B7\u00B2
#'   effect size indicator
#' @param omegasq \code{TRUE} or \code{FALSE} (default), provides \u03C9\u00B2
#'   effect size indicator
#' @param kwind \code{TRUE} or \code{FALSE} (default), provides Kruskal-Wallis
#'   effect size indicator
#' @param hist \code{TRUE} or \code{FALSE} (default), provides histograms
#'   (continuous variables only)
#' @param dens \code{TRUE} or \code{FALSE} (default), provides density plots
#'   (continuous variables only)
#' @param norm \code{TRUE} or \code{FALSE} (default), provides overlapped
#'   normal curve (continuous variables only)
#' @param box \code{TRUE} or \code{FALSE} (default), provide box plots
#'   (continuous variables only)
#' @param violin \code{TRUE} or \code{FALSE} (default), provide violin plots
#'   (continuous variables only)
#' @param dot \code{TRUE} or \code{FALSE} (default), provide dot plots
#'   (continuous variables only)
#' @param dotType .
#' @param boxMean \code{TRUE} or \code{FALSE} (default), add mean to box plot
#' @param innerf a number (detects by default the number) specifying the inner
#'   fence for detecting outliers
#' @param outerf a number (detects by default the number) specifying the outer
#'   fence for detecting outliers
#' @param qq \code{TRUE} or \code{FALSE} (default), provide Q-Q plots
#'   (continuous variables only)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$indicesnum} \tab \tab \tab \tab \tab A table of the descriptive statistics \cr
#'   \code{results$esindices} \tab \tab \tab \tab \tab A table of different effect size indicators \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab An array of descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$indicesnum$asDF}
#'
#' \code{as.data.frame(results$indicesnum)}
#'
#' @export
bivmix <- function(
    data,
    vars,
    groupBy = NULL,
    n = FALSE,
    missing = FALSE,
    mean = FALSE,
    median = FALSE,
    mode = FALSE,
    geommean = FALSE,
    trimean = FALSE,
    avquartile = FALSE,
    midrange = FALSE,
    trimmean = FALSE,
    Trim = 5,
    winsmean = FALSE,
    Win = 5,
    variance = FALSE,
    stddev = FALSE,
    geomsd = FALSE,
    meandev = FALSE,
    cv = FALSE,
    range = FALSE,
    iqr = FALSE,
    qd = FALSE,
    mad = FALSE,
    rcv = FALSE,
    irange = FALSE,
    NPerc = 90,
    min = FALSE,
    max = FALSE,
    q1 = FALSE,
    q2 = FALSE,
    q3 = FALSE,
    beta1 = FALSE,
    gamma1 = FALSE,
    h1 = FALSE,
    h3 = FALSE,
    beta2 = FALSE,
    gamma2 = FALSE,
    k2 = FALSE,
    k3 = FALSE,
    pc = FALSE,
    pcValues = "25,50,75",
    cohend = FALSE,
    rbp = FALSE,
    probsup = FALSE,
    etasq = FALSE,
    omegasq = FALSE,
    kwind = FALSE,
    hist = FALSE,
    dens = FALSE,
    norm = FALSE,
    box = FALSE,
    violin = FALSE,
    dot = FALSE,
    dotType = "jitter",
    boxMean = FALSE,
    innerf = 1.5,
    outerf = 3,
    qq = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bivmix requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(groupBy)) groupBy <- jmvcore::resolveQuo(jmvcore::enquo(groupBy))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(groupBy), groupBy, NULL))

    for (v in groupBy) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- bivmixOptions$new(
        vars = vars,
        groupBy = groupBy,
        n = n,
        missing = missing,
        mean = mean,
        median = median,
        mode = mode,
        geommean = geommean,
        trimean = trimean,
        avquartile = avquartile,
        midrange = midrange,
        trimmean = trimmean,
        Trim = Trim,
        winsmean = winsmean,
        Win = Win,
        variance = variance,
        stddev = stddev,
        geomsd = geomsd,
        meandev = meandev,
        cv = cv,
        range = range,
        iqr = iqr,
        qd = qd,
        mad = mad,
        rcv = rcv,
        irange = irange,
        NPerc = NPerc,
        min = min,
        max = max,
        q1 = q1,
        q2 = q2,
        q3 = q3,
        beta1 = beta1,
        gamma1 = gamma1,
        h1 = h1,
        h3 = h3,
        beta2 = beta2,
        gamma2 = gamma2,
        k2 = k2,
        k3 = k3,
        pc = pc,
        pcValues = pcValues,
        cohend = cohend,
        rbp = rbp,
        probsup = probsup,
        etasq = etasq,
        omegasq = omegasq,
        kwind = kwind,
        hist = hist,
        dens = dens,
        norm = norm,
        box = box,
        violin = violin,
        dot = dot,
        dotType = dotType,
        boxMean = boxMean,
        innerf = innerf,
        outerf = outerf,
        qq = qq)

    analysis <- bivmixClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

