
# This file is automatically generated, you probably don't want to edit this

catSummaryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "catSummaryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            freq = FALSE,
            mode = FALSE,
            VR = FALSE,
            Blau = FALSE,
            Teachman = FALSE,
            IQV = FALSE,
            NCat = 0,
            bar = FALSE,
            f2p.bar = "absolutefreq",
            pie = FALSE,
            pareto = FALSE,
            lolli = FALSE,
            f2p.lolli = "absolutefreq",
            dough = FALSE, ...) {

            super$initialize(
                package="saRa",
                name="catSummary",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..freq <- jmvcore::OptionBool$new(
                "freq",
                freq,
                default=FALSE)
            private$..mode <- jmvcore::OptionBool$new(
                "mode",
                mode,
                default=FALSE)
            private$..VR <- jmvcore::OptionBool$new(
                "VR",
                VR,
                default=FALSE)
            private$..Blau <- jmvcore::OptionBool$new(
                "Blau",
                Blau,
                default=FALSE)
            private$..Teachman <- jmvcore::OptionBool$new(
                "Teachman",
                Teachman,
                default=FALSE)
            private$..IQV <- jmvcore::OptionBool$new(
                "IQV",
                IQV,
                default=FALSE)
            private$..NCat <- jmvcore::OptionInteger$new(
                "NCat",
                NCat,
                default=0)
            private$..bar <- jmvcore::OptionBool$new(
                "bar",
                bar,
                default=FALSE)
            private$..f2p.bar <- jmvcore::OptionList$new(
                "f2p.bar",
                f2p.bar,
                options=list(
                    "absolutefreq",
                    "relativefreq"),
                default="absolutefreq")
            private$..pie <- jmvcore::OptionBool$new(
                "pie",
                pie,
                default=FALSE)
            private$..pareto <- jmvcore::OptionBool$new(
                "pareto",
                pareto,
                default=FALSE)
            private$..lolli <- jmvcore::OptionBool$new(
                "lolli",
                lolli,
                default=FALSE)
            private$..f2p.lolli <- jmvcore::OptionList$new(
                "f2p.lolli",
                f2p.lolli,
                options=list(
                    "absolutefreq",
                    "relativefreq"),
                default="absolutefreq")
            private$..dough <- jmvcore::OptionBool$new(
                "dough",
                dough,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..freq)
            self$.addOption(private$..mode)
            self$.addOption(private$..VR)
            self$.addOption(private$..Blau)
            self$.addOption(private$..Teachman)
            self$.addOption(private$..IQV)
            self$.addOption(private$..NCat)
            self$.addOption(private$..bar)
            self$.addOption(private$..f2p.bar)
            self$.addOption(private$..pie)
            self$.addOption(private$..pareto)
            self$.addOption(private$..lolli)
            self$.addOption(private$..f2p.lolli)
            self$.addOption(private$..dough)
        }),
    active = list(
        vars = function() private$..vars$value,
        freq = function() private$..freq$value,
        mode = function() private$..mode$value,
        VR = function() private$..VR$value,
        Blau = function() private$..Blau$value,
        Teachman = function() private$..Teachman$value,
        IQV = function() private$..IQV$value,
        NCat = function() private$..NCat$value,
        bar = function() private$..bar$value,
        f2p.bar = function() private$..f2p.bar$value,
        pie = function() private$..pie$value,
        pareto = function() private$..pareto$value,
        lolli = function() private$..lolli$value,
        f2p.lolli = function() private$..f2p.lolli$value,
        dough = function() private$..dough$value),
    private = list(
        ..vars = NA,
        ..freq = NA,
        ..mode = NA,
        ..VR = NA,
        ..Blau = NA,
        ..Teachman = NA,
        ..IQV = NA,
        ..NCat = NA,
        ..bar = NA,
        ..f2p.bar = NA,
        ..pie = NA,
        ..pareto = NA,
        ..lolli = NA,
        ..f2p.lolli = NA,
        ..dough = NA)
)

catSummaryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "catSummaryResults",
    inherit = jmvcore::Group,
    active = list(
        indices = function() private$.items[["indices"]],
        frequencies = function() private$.items[["frequencies"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Univariate Data Analysis (Categorical Data)")
            self$add(jmvcore::Table$new(
                options=options,
                name="indices",
                title="Descriptives",
                visible="(mode || VR || Blau || Teachman || IQV)",
                rows=1,
                columns=list()))
            self$add(jmvcore::Array$new(
                options=options,
                name="frequencies",
                title="Frequencies distribution",
                visible="(freq)",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Frequencies and Odds of $key",
                    visible="(levels($key))",
                    columns=list())))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="($key)")}))$new(options=options)))}))

catSummaryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "catSummaryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "catSummary",
                version = c(0,1,0),
                options = options,
                results = catSummaryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Categorical Data
#'
#' 
#' @param data .
#' @param vars a vector of strings naming the variables of interest in
#'   \code{data}
#' @param freq \code{TRUE} or \code{FALSE} (default), provide frequency tables
#'   (nominal, ordinal variables only) - name: mode
#' @param mode \code{TRUE} or \code{FALSE} (default), provide the mode
#' @param VR \code{TRUE} (default) or \code{FALSE}, provide the variation
#'   ratio
#' @param Blau \code{TRUE} (default) or \code{FALSE}, provide the Blau's Index
#' @param Teachman \code{TRUE} (default) or \code{FALSE}, provide the
#'   Teachman's Index
#' @param IQV \code{TRUE} (default) or \code{FALSE}, provide the Index
#'   Qualitative Variation
#' @param NCat an integer (detects by default the number) specifying the
#'   number of categories
#' @param bar \code{TRUE} or \code{FALSE} (default), provide bar plots
#' @param f2p.bar \code{'absolute'} (default) or \code{'relative'}
#'   frequencies, to be used when plotting barplots.
#' @param pie \code{TRUE} or \code{FALSE} (default), provide pie charts
#' @param pareto \code{TRUE} or \code{FALSE} (default), provide Pareto charts
#' @param lolli \code{TRUE} or \code{FALSE} (default), provide Lollipop charts
#' @param f2p.lolli \code{'absolute'} (default) or \code{'relative'}
#'   frequencies, to be used when plotting lollipop plots.
#' @param dough \code{TRUE} or \code{FALSE} (default), provide doughnut charts
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$indices} \tab \tab \tab \tab \tab A table of the descriptive statistics \cr
#'   \code{results$frequencies} \tab \tab \tab \tab \tab Frequencies Distribution \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab An array of descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$indices$asDF}
#'
#' \code{as.data.frame(results$indices)}
#'
#' @export
catSummary <- function(
    data,
    vars,
    freq = FALSE,
    mode = FALSE,
    VR = FALSE,
    Blau = FALSE,
    Teachman = FALSE,
    IQV = FALSE,
    NCat = 0,
    bar = FALSE,
    f2p.bar = "absolutefreq",
    pie = FALSE,
    pareto = FALSE,
    lolli = FALSE,
    f2p.lolli = "absolutefreq",
    dough = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("catSummary requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- catSummaryOptions$new(
        vars = vars,
        freq = freq,
        mode = mode,
        VR = VR,
        Blau = Blau,
        Teachman = Teachman,
        IQV = IQV,
        NCat = NCat,
        bar = bar,
        f2p.bar = f2p.bar,
        pie = pie,
        pareto = pareto,
        lolli = lolli,
        f2p.lolli = f2p.lolli,
        dough = dough)

    analysis <- catSummaryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

