
# This file is automatically generated, you probably don't want to edit this

contvarsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contvarsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="saRa",
                name="contvars",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

contvarsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contvarsResults",
    inherit = jmvcore::Group,
    active = list(
        frequencies = function() private$.items[["frequencies"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Distributions")
            self$add(jmvcore::Array$new(
                options=options,
                name="frequencies",
                title="Categorical Data",
                visible="(freq)",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Frequencies and odds of $key",
                    visible="(levels($key))",
                    columns=list())))}))

contvarsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contvarsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "contvars",
                version = c(0,1,0),
                options = options,
                results = contvarsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Continuous Distributions
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$frequencies} \tab \tab \tab \tab \tab Frequencies Distribution \cr
#' }
#'
#' @export
contvars <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("contvars requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- contvarsOptions$new()

    analysis <- contvarsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

