
# This file is automatically generated, you probably don't want to edit this

discvarsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "discvarsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            distros = "binom",
            binomn = 10,
            binomp = 0.5,
            lambda = 10,
            negbinomr = 10,
            negbinomp = 0.5,
            geomp = 0.5,
            valuesfunc = NULL,
            pmf = FALSE,
            cdf = FALSE,
            surv = FALSE,
            icdf = FALSE,
            qvalues = NULL,
            ppvalue = NULL,
            ppmf = FALSE,
            pcdf = FALSE,
            pinterv = FALSE,
            x1value = NULL,
            x2value = NULL,
            psurv = FALSE,
            picdf = FALSE,
            pqvalue = NULL,
            tail = "left", ...) {

            super$initialize(
                package="saRa",
                name="discvars",
                requiresData=FALSE,
                ...)

            private$..distros <- jmvcore::OptionList$new(
                "distros",
                distros,
                options=list(
                    "binom",
                    "poiss",
                    "negbinom",
                    "geom"),
                default="binom")
            private$..binomn <- jmvcore::OptionInteger$new(
                "binomn",
                binomn,
                default=10)
            private$..binomp <- jmvcore::OptionNumber$new(
                "binomp",
                binomp,
                default=0.5)
            private$..lambda <- jmvcore::OptionNumber$new(
                "lambda",
                lambda,
                default=10)
            private$..negbinomr <- jmvcore::OptionInteger$new(
                "negbinomr",
                negbinomr,
                default=10)
            private$..negbinomp <- jmvcore::OptionNumber$new(
                "negbinomp",
                negbinomp,
                default=0.5)
            private$..geomp <- jmvcore::OptionNumber$new(
                "geomp",
                geomp,
                default=0.5)
            private$..valuesfunc <- jmvcore::OptionString$new(
                "valuesfunc",
                valuesfunc)
            private$..pmf <- jmvcore::OptionBool$new(
                "pmf",
                pmf,
                default=FALSE)
            private$..cdf <- jmvcore::OptionBool$new(
                "cdf",
                cdf,
                default=FALSE)
            private$..surv <- jmvcore::OptionBool$new(
                "surv",
                surv,
                default=FALSE)
            private$..icdf <- jmvcore::OptionBool$new(
                "icdf",
                icdf,
                default=FALSE)
            private$..qvalues <- jmvcore::OptionString$new(
                "qvalues",
                qvalues)
            private$..ppvalue <- jmvcore::OptionNumber$new(
                "ppvalue",
                ppvalue)
            private$..ppmf <- jmvcore::OptionBool$new(
                "ppmf",
                ppmf,
                default=FALSE)
            private$..pcdf <- jmvcore::OptionBool$new(
                "pcdf",
                pcdf,
                default=FALSE)
            private$..pinterv <- jmvcore::OptionBool$new(
                "pinterv",
                pinterv,
                default=FALSE)
            private$..x1value <- jmvcore::OptionNumber$new(
                "x1value",
                x1value)
            private$..x2value <- jmvcore::OptionNumber$new(
                "x2value",
                x2value)
            private$..psurv <- jmvcore::OptionBool$new(
                "psurv",
                psurv,
                default=FALSE)
            private$..picdf <- jmvcore::OptionBool$new(
                "picdf",
                picdf,
                default=FALSE)
            private$..pqvalue <- jmvcore::OptionNumber$new(
                "pqvalue",
                pqvalue)
            private$..tail <- jmvcore::OptionList$new(
                "tail",
                tail,
                options=list(
                    "left",
                    "right",
                    "central"),
                default="left")

            self$.addOption(private$..distros)
            self$.addOption(private$..binomn)
            self$.addOption(private$..binomp)
            self$.addOption(private$..lambda)
            self$.addOption(private$..negbinomr)
            self$.addOption(private$..negbinomp)
            self$.addOption(private$..geomp)
            self$.addOption(private$..valuesfunc)
            self$.addOption(private$..pmf)
            self$.addOption(private$..cdf)
            self$.addOption(private$..surv)
            self$.addOption(private$..icdf)
            self$.addOption(private$..qvalues)
            self$.addOption(private$..ppvalue)
            self$.addOption(private$..ppmf)
            self$.addOption(private$..pcdf)
            self$.addOption(private$..pinterv)
            self$.addOption(private$..x1value)
            self$.addOption(private$..x2value)
            self$.addOption(private$..psurv)
            self$.addOption(private$..picdf)
            self$.addOption(private$..pqvalue)
            self$.addOption(private$..tail)
        }),
    active = list(
        distros = function() private$..distros$value,
        binomn = function() private$..binomn$value,
        binomp = function() private$..binomp$value,
        lambda = function() private$..lambda$value,
        negbinomr = function() private$..negbinomr$value,
        negbinomp = function() private$..negbinomp$value,
        geomp = function() private$..geomp$value,
        valuesfunc = function() private$..valuesfunc$value,
        pmf = function() private$..pmf$value,
        cdf = function() private$..cdf$value,
        surv = function() private$..surv$value,
        icdf = function() private$..icdf$value,
        qvalues = function() private$..qvalues$value,
        ppvalue = function() private$..ppvalue$value,
        ppmf = function() private$..ppmf$value,
        pcdf = function() private$..pcdf$value,
        pinterv = function() private$..pinterv$value,
        x1value = function() private$..x1value$value,
        x2value = function() private$..x2value$value,
        psurv = function() private$..psurv$value,
        picdf = function() private$..picdf$value,
        pqvalue = function() private$..pqvalue$value,
        tail = function() private$..tail$value),
    private = list(
        ..distros = NA,
        ..binomn = NA,
        ..binomp = NA,
        ..lambda = NA,
        ..negbinomr = NA,
        ..negbinomp = NA,
        ..geomp = NA,
        ..valuesfunc = NA,
        ..pmf = NA,
        ..cdf = NA,
        ..surv = NA,
        ..icdf = NA,
        ..qvalues = NA,
        ..ppvalue = NA,
        ..ppmf = NA,
        ..pcdf = NA,
        ..pinterv = NA,
        ..x1value = NA,
        ..x2value = NA,
        ..psurv = NA,
        ..picdf = NA,
        ..pqvalue = NA,
        ..tail = NA)
)

discvarsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "discvarsResults",
    inherit = jmvcore::Group,
    active = list(
        InfoTab = function() private$.items[["InfoTab"]],
        probstab = function() private$.items[["probstab"]],
        quantstab = function() private$.items[["quantstab"]],
        pmfplot = function() private$.items[["pmfplot"]],
        cdfplot = function() private$.items[["cdfplot"]],
        survplot = function() private$.items[["survplot"]],
        intervplot = function() private$.items[["intervplot"]],
        icdfplot = function() private$.items[["icdfplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Discrete Distributions")
            self$add(jmvcore::Table$new(
                options=options,
                name="InfoTab",
                title="Distribution information",
                rows=1,
                columns=list(
                    list(
                        `name`="DistributionColumn", 
                        `title`="Distribution", 
                        `type`="text"),
                    list(
                        `name`="ParametersColumn", 
                        `title`="Parameter(s)", 
                        `type`="text", 
                        `visible`="(distros)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="probstab",
                title="Probabilities table",
                visible="(pmf | cdf | surv)",
                rows=1,
                columns=list(
                    list(
                        `name`="varValues", 
                        `title`="x", 
                        `type`="text", 
                        `visible`="(distros)"),
                    list(
                        `name`="pmf", 
                        `title`="Pr(X = x)", 
                        `type`="number", 
                        `visible`="(pmf)"),
                    list(
                        `name`="cdf", 
                        `title`="Pr(X \u2264 x)", 
                        `type`="number", 
                        `visible`="(cdf)"),
                    list(
                        `name`="surv", 
                        `title`="Pr(X > x)", 
                        `type`="number", 
                        `visible`="(surv)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="quantstab",
                title="Quantiles table",
                visible="(icdf)",
                rows=1,
                columns=list(
                    list(
                        `name`="quantValues", 
                        `title`="Prob", 
                        `type`="text", 
                        `visible`="(distros)"),
                    list(
                        `name`="lTail", 
                        `title`="Left tail", 
                        `type`="number", 
                        `visible`="(icdf)"),
                    list(
                        `name`="rTail", 
                        `title`="Right tail", 
                        `type`="number", 
                        `visible`="(icdf)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="pmfplot",
                title="Probability mass function plot",
                width=450,
                height=400,
                renderFun=".ppmf",
                visible="(ppmf)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="cdfplot",
                title="Cumulative distribution function plot",
                width=450,
                height=400,
                renderFun=".pcdf",
                visible="(pcdf)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="survplot",
                title="Survival function plot",
                width=450,
                height=400,
                renderFun=".psurv",
                visible="(psurv)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="intervplot",
                title="Probability interval plot",
                width=450,
                height=400,
                renderFun=".pinterv",
                visible="(pinterv)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="icdfplot",
                title="Quantile (ICDF) plot",
                width=450,
                height=400,
                renderFun=".picdf",
                visible="(picdf)"))}))

discvarsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "discvarsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "discvars",
                version = c(0,1,0),
                options = options,
                results = discvarsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Discrete Distributions
#'
#' 
#' @param distros \code{binom} (default), \code{poiss}, 'negbinom', 'geom', or
#'   \code{hypergeom}, specifies binomial, poisson, negative binomial, geometric
#'   or hypergeometric distributions
#' @param binomn a number specifying number of trials in binomial distribution
#' @param binomp a number specifying success probability in binomial
#'   distribution
#' @param lambda lambda parameter for Poisson distribution
#' @param negbinomr a number specifying number of successes in negative
#'   binomial distribution
#' @param negbinomp a number specifying success probability in negative
#'   binomial distribution
#' @param geomp a number specifying success probability in geometric
#'   distribution
#' @param valuesfunc a comma-separated list specifying random variables'
#'   values
#' @param pmf \code{TRUE} or \code{FALSE} (default), provide probability mass
#'   function for a discrete distribution
#' @param cdf \code{TRUE} or \code{FALSE} (default), provide cumulative
#'   distribution function for a discrete distribution
#' @param surv \code{TRUE} or \code{FALSE} (default), provide survival
#'   function for a discrete distribution
#' @param icdf \code{TRUE} or \code{FALSE} (default), provide inverse of
#'   cumulative distribution function for a discrete distribution
#' @param qvalues a comma-separated list specifying quantiles for a random
#'   variable
#' @param ppvalue a number specifying random variables' value to be plotted
#' @param ppmf \code{TRUE} or \code{FALSE} (default), provide probability mass
#'   function for a discrete distribution to be plotted
#' @param pcdf \code{TRUE} or \code{FALSE} (default), provide cumulative
#'   distribution function for a discrete distribution to be plotted
#' @param pinterv \code{TRUE} or \code{FALSE} (default), provide probability
#'   plot within an interval
#' @param x1value a number specifying X1 value for probability plot within
#'   interval
#' @param x2value a number specifying X2 value for probability plot within
#'   interval
#' @param psurv \code{TRUE} or \code{FALSE} (default), provide survival
#'   function for a discrete distribution to be plotted
#' @param picdf \code{TRUE} or \code{FALSE} (default), provide inverse of
#'   cumulative distribution function for a discrete distribution to be plotted
#' @param pqvalue a number specifying a quantile for a random variable to be
#'   plotted
#' @param tail \code{left} (default), \code{right}, or \code{central},
#'   specifies the tail to be plotted in the ICDF plot for discrete
#'   distributions
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$InfoTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$probstab} \tab \tab \tab \tab \tab A table with probabilities for selected distributions \cr
#'   \code{results$quantstab} \tab \tab \tab \tab \tab A table with quantiles for selected distributions \cr
#'   \code{results$pmfplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cdfplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$survplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$intervplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$icdfplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$InfoTab$asDF}
#'
#' \code{as.data.frame(results$InfoTab)}
#'
#' @export
discvars <- function(
    distros = "binom",
    binomn = 10,
    binomp = 0.5,
    lambda = 10,
    negbinomr = 10,
    negbinomp = 0.5,
    geomp = 0.5,
    valuesfunc,
    pmf = FALSE,
    cdf = FALSE,
    surv = FALSE,
    icdf = FALSE,
    qvalues,
    ppvalue,
    ppmf = FALSE,
    pcdf = FALSE,
    pinterv = FALSE,
    x1value,
    x2value,
    psurv = FALSE,
    picdf = FALSE,
    pqvalue,
    tail = "left") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("discvars requires jmvcore to be installed (restart may be required)")


    options <- discvarsOptions$new(
        distros = distros,
        binomn = binomn,
        binomp = binomp,
        lambda = lambda,
        negbinomr = negbinomr,
        negbinomp = negbinomp,
        geomp = geomp,
        valuesfunc = valuesfunc,
        pmf = pmf,
        cdf = cdf,
        surv = surv,
        icdf = icdf,
        qvalues = qvalues,
        ppvalue = ppvalue,
        ppmf = ppmf,
        pcdf = pcdf,
        pinterv = pinterv,
        x1value = x1value,
        x2value = x2value,
        psurv = psurv,
        picdf = picdf,
        pqvalue = pqvalue,
        tail = tail)

    analysis <- discvarsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

