
# This file is automatically generated, you probably don't want to edit this

ordSummaryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordSummaryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            n = FALSE,
            missing = FALSE,
            median = FALSE,
            mode = FALSE,
            trimean = FALSE,
            avquartile = FALSE,
            midrange = FALSE,
            range = FALSE,
            iqr = FALSE,
            qd = FALSE,
            mad = FALSE,
            rcv = FALSE,
            irange = FALSE,
            NPerc = 90,
            min = FALSE,
            max = FALSE,
            q1 = FALSE,
            q2 = FALSE,
            q3 = FALSE,
            pc = FALSE,
            pcValues = "25,50,75",
            h1 = FALSE,
            h3 = FALSE,
            k2 = FALSE,
            k3 = FALSE,
            bar = FALSE,
            f2p.bar = "absolutefreq",
            box = FALSE,
            violin = FALSE,
            dot = FALSE,
            dotType = "jitter",
            boxMean = FALSE,
            innerf = 1.5,
            outerf = 3, ...) {

            super$initialize(
                package="saRa",
                name="ordSummary",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..n <- jmvcore::OptionBool$new(
                "n",
                n,
                default=FALSE)
            private$..missing <- jmvcore::OptionBool$new(
                "missing",
                missing,
                default=FALSE)
            private$..median <- jmvcore::OptionBool$new(
                "median",
                median,
                default=FALSE)
            private$..mode <- jmvcore::OptionBool$new(
                "mode",
                mode,
                default=FALSE)
            private$..trimean <- jmvcore::OptionBool$new(
                "trimean",
                trimean,
                default=FALSE)
            private$..avquartile <- jmvcore::OptionBool$new(
                "avquartile",
                avquartile,
                default=FALSE)
            private$..midrange <- jmvcore::OptionBool$new(
                "midrange",
                midrange,
                default=FALSE)
            private$..range <- jmvcore::OptionBool$new(
                "range",
                range,
                default=FALSE)
            private$..iqr <- jmvcore::OptionBool$new(
                "iqr",
                iqr,
                default=FALSE)
            private$..qd <- jmvcore::OptionBool$new(
                "qd",
                qd,
                default=FALSE)
            private$..mad <- jmvcore::OptionBool$new(
                "mad",
                mad,
                default=FALSE)
            private$..rcv <- jmvcore::OptionBool$new(
                "rcv",
                rcv,
                default=FALSE)
            private$..irange <- jmvcore::OptionBool$new(
                "irange",
                irange,
                default=FALSE)
            private$..NPerc <- jmvcore::OptionInteger$new(
                "NPerc",
                NPerc,
                default=90)
            private$..min <- jmvcore::OptionBool$new(
                "min",
                min,
                default=FALSE)
            private$..max <- jmvcore::OptionBool$new(
                "max",
                max,
                default=FALSE)
            private$..q1 <- jmvcore::OptionBool$new(
                "q1",
                q1,
                default=FALSE)
            private$..q2 <- jmvcore::OptionBool$new(
                "q2",
                q2,
                default=FALSE)
            private$..q3 <- jmvcore::OptionBool$new(
                "q3",
                q3,
                default=FALSE)
            private$..pc <- jmvcore::OptionBool$new(
                "pc",
                pc,
                default=FALSE)
            private$..pcValues <- jmvcore::OptionString$new(
                "pcValues",
                pcValues,
                default="25,50,75")
            private$..h1 <- jmvcore::OptionBool$new(
                "h1",
                h1,
                default=FALSE)
            private$..h3 <- jmvcore::OptionBool$new(
                "h3",
                h3,
                default=FALSE)
            private$..k2 <- jmvcore::OptionBool$new(
                "k2",
                k2,
                default=FALSE)
            private$..k3 <- jmvcore::OptionBool$new(
                "k3",
                k3,
                default=FALSE)
            private$..bar <- jmvcore::OptionBool$new(
                "bar",
                bar,
                default=FALSE)
            private$..f2p.bar <- jmvcore::OptionList$new(
                "f2p.bar",
                f2p.bar,
                options=list(
                    "absolutefreq",
                    "relativefreq"),
                default="absolutefreq")
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)
            private$..violin <- jmvcore::OptionBool$new(
                "violin",
                violin,
                default=FALSE)
            private$..dot <- jmvcore::OptionBool$new(
                "dot",
                dot,
                default=FALSE)
            private$..dotType <- jmvcore::OptionList$new(
                "dotType",
                dotType,
                options=list(
                    "jitter",
                    "stack"),
                default="jitter")
            private$..boxMean <- jmvcore::OptionBool$new(
                "boxMean",
                boxMean,
                default=FALSE)
            private$..innerf <- jmvcore::OptionNumber$new(
                "innerf",
                innerf,
                default=1.5)
            private$..outerf <- jmvcore::OptionNumber$new(
                "outerf",
                outerf,
                default=3)

            self$.addOption(private$..vars)
            self$.addOption(private$..n)
            self$.addOption(private$..missing)
            self$.addOption(private$..median)
            self$.addOption(private$..mode)
            self$.addOption(private$..trimean)
            self$.addOption(private$..avquartile)
            self$.addOption(private$..midrange)
            self$.addOption(private$..range)
            self$.addOption(private$..iqr)
            self$.addOption(private$..qd)
            self$.addOption(private$..mad)
            self$.addOption(private$..rcv)
            self$.addOption(private$..irange)
            self$.addOption(private$..NPerc)
            self$.addOption(private$..min)
            self$.addOption(private$..max)
            self$.addOption(private$..q1)
            self$.addOption(private$..q2)
            self$.addOption(private$..q3)
            self$.addOption(private$..pc)
            self$.addOption(private$..pcValues)
            self$.addOption(private$..h1)
            self$.addOption(private$..h3)
            self$.addOption(private$..k2)
            self$.addOption(private$..k3)
            self$.addOption(private$..bar)
            self$.addOption(private$..f2p.bar)
            self$.addOption(private$..box)
            self$.addOption(private$..violin)
            self$.addOption(private$..dot)
            self$.addOption(private$..dotType)
            self$.addOption(private$..boxMean)
            self$.addOption(private$..innerf)
            self$.addOption(private$..outerf)
        }),
    active = list(
        vars = function() private$..vars$value,
        n = function() private$..n$value,
        missing = function() private$..missing$value,
        median = function() private$..median$value,
        mode = function() private$..mode$value,
        trimean = function() private$..trimean$value,
        avquartile = function() private$..avquartile$value,
        midrange = function() private$..midrange$value,
        range = function() private$..range$value,
        iqr = function() private$..iqr$value,
        qd = function() private$..qd$value,
        mad = function() private$..mad$value,
        rcv = function() private$..rcv$value,
        irange = function() private$..irange$value,
        NPerc = function() private$..NPerc$value,
        min = function() private$..min$value,
        max = function() private$..max$value,
        q1 = function() private$..q1$value,
        q2 = function() private$..q2$value,
        q3 = function() private$..q3$value,
        pc = function() private$..pc$value,
        pcValues = function() private$..pcValues$value,
        h1 = function() private$..h1$value,
        h3 = function() private$..h3$value,
        k2 = function() private$..k2$value,
        k3 = function() private$..k3$value,
        bar = function() private$..bar$value,
        f2p.bar = function() private$..f2p.bar$value,
        box = function() private$..box$value,
        violin = function() private$..violin$value,
        dot = function() private$..dot$value,
        dotType = function() private$..dotType$value,
        boxMean = function() private$..boxMean$value,
        innerf = function() private$..innerf$value,
        outerf = function() private$..outerf$value),
    private = list(
        ..vars = NA,
        ..n = NA,
        ..missing = NA,
        ..median = NA,
        ..mode = NA,
        ..trimean = NA,
        ..avquartile = NA,
        ..midrange = NA,
        ..range = NA,
        ..iqr = NA,
        ..qd = NA,
        ..mad = NA,
        ..rcv = NA,
        ..irange = NA,
        ..NPerc = NA,
        ..min = NA,
        ..max = NA,
        ..q1 = NA,
        ..q2 = NA,
        ..q3 = NA,
        ..pc = NA,
        ..pcValues = NA,
        ..h1 = NA,
        ..h3 = NA,
        ..k2 = NA,
        ..k3 = NA,
        ..bar = NA,
        ..f2p.bar = NA,
        ..box = NA,
        ..violin = NA,
        ..dot = NA,
        ..dotType = NA,
        ..boxMean = NA,
        ..innerf = NA,
        ..outerf = NA)
)

ordSummaryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordSummaryResults",
    inherit = jmvcore::Group,
    active = list(
        indicesord = function() private$.items[["indicesord"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Univariate Data Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="indicesord",
                title="Statistics",
                visible="(n || missing || median || mode || trimean || avquartile || midrange || range || iqr || qd || mad || rcv || min || max || q1 || q2 || q3 || pc || irange || h1 || h3 || k2 || k3)",
                rows=1,
                clearWith=list(
                    "pcValues",
                    "NPerc"),
                columns=list()))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                clearWith=list(
                    "innerf",
                    "outerf"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="($key)")}))$new(options=options)))}))

ordSummaryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ordSummaryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "saRa",
                name = "ordSummary",
                version = c(0,1,0),
                options = options,
                results = ordSummaryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Ordinal Data
#'
#' 
#' @param data .
#' @param vars a vector of strings naming the variables of interest in
#'   \code{data}
#' @param n \code{TRUE} or \code{FALSE} (default), provide the N
#' @param missing \code{TRUE} or \code{FALSE} (default), provide the missing
#'   values
#' @param median \code{TRUE} or \code{FALSE} (default), provide the median
#' @param mode \code{TRUE} or \code{FALSE} (default), provide the mode
#' @param trimean \code{TRUE} or \code{FALSE} (default), provide the trimean
#' @param avquartile \code{TRUE} or \code{FALSE} (default), provide the
#'   quartiles average
#' @param midrange \code{TRUE} or \code{FALSE} (default), provide the
#'   mid-range
#' @param range \code{TRUE} or \code{FALSE} (default), provide the range
#' @param iqr \code{TRUE} or \code{FALSE} (default), provide the iqr
#' @param qd \code{TRUE} or \code{FALSE} (default), provide the quartile
#'   deviation
#' @param mad \code{TRUE} or \code{FALSE} (default), provide the mad
#' @param rcv \code{TRUE} or \code{FALSE} (default), provide the rcv
#' @param irange \code{TRUE} (default) or \code{FALSE}, provide the Inner
#'   Range
#' @param NPerc an integer (detects by default the number) specifying the
#'   percentage of data used
#' @param min \code{TRUE} or \code{FALSE} (default), provide the minimum
#' @param max \code{TRUE} or \code{FALSE} (default), provide the maximum
#' @param q1 \code{TRUE} or \code{FALSE} (default), provide the first quartile
#' @param q2 \code{TRUE} or \code{FALSE} (default), provide the second
#'   quartile
#' @param q3 \code{TRUE} or \code{FALSE} (default), provide the third quartile
#' @param pc \code{TRUE} or \code{FALSE} (default), provide the Percentiles
#' @param pcValues a comma-separated list (default: 25,50,75) specifying the
#'   percentiles
#' @param h1 \code{TRUE} or \code{FALSE} (default), provide the H1 index
#' @param h3 \code{TRUE} or \code{FALSE} (default), provide the H3 index
#' @param k2 \code{TRUE} or \code{FALSE} (default), provide the K2 index
#' @param k3 \code{TRUE} or \code{FALSE} (default), provide the K3 index
#' @param bar \code{TRUE} or \code{FALSE} (default), provide bar plots
#' @param f2p.bar \code{'absolute'} (default) or \code{'relative'}
#'   frequencies, to be used when plotting barplots.
#' @param box \code{TRUE} or \code{FALSE} (default), provide box plots
#'   (continuous variables only)
#' @param violin \code{TRUE} or \code{FALSE} (default), provide violin plots
#'   (continuous variables only)
#' @param dot \code{TRUE} or \code{FALSE} (default), provide dot plots
#'   (continuous variables only)
#' @param dotType .
#' @param boxMean \code{TRUE} or \code{FALSE} (default), add mean to box plot
#' @param innerf a number (detects by default the number) specifying the inner
#'   fence for detecting outliers
#' @param outerf a number (detects by default the number) specifying the outer
#'   fence for detecting outliers
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$indicesord} \tab \tab \tab \tab \tab A table of the descriptive statistics \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab An array of descriptive plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$indicesord$asDF}
#'
#' \code{as.data.frame(results$indicesord)}
#'
#' @export
ordSummary <- function(
    data,
    vars,
    n = FALSE,
    missing = FALSE,
    median = FALSE,
    mode = FALSE,
    trimean = FALSE,
    avquartile = FALSE,
    midrange = FALSE,
    range = FALSE,
    iqr = FALSE,
    qd = FALSE,
    mad = FALSE,
    rcv = FALSE,
    irange = FALSE,
    NPerc = 90,
    min = FALSE,
    max = FALSE,
    q1 = FALSE,
    q2 = FALSE,
    q3 = FALSE,
    pc = FALSE,
    pcValues = "25,50,75",
    h1 = FALSE,
    h3 = FALSE,
    k2 = FALSE,
    k3 = FALSE,
    bar = FALSE,
    f2p.bar = "absolutefreq",
    box = FALSE,
    violin = FALSE,
    dot = FALSE,
    dotType = "jitter",
    boxMean = FALSE,
    innerf = 1.5,
    outerf = 3) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ordSummary requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- ordSummaryOptions$new(
        vars = vars,
        n = n,
        missing = missing,
        median = median,
        mode = mode,
        trimean = trimean,
        avquartile = avquartile,
        midrange = midrange,
        range = range,
        iqr = iqr,
        qd = qd,
        mad = mad,
        rcv = rcv,
        irange = irange,
        NPerc = NPerc,
        min = min,
        max = max,
        q1 = q1,
        q2 = q2,
        q3 = q3,
        pc = pc,
        pcValues = pcValues,
        h1 = h1,
        h3 = h3,
        k2 = k2,
        k3 = k3,
        bar = bar,
        f2p.bar = f2p.bar,
        box = box,
        violin = violin,
        dot = dot,
        dotType = dotType,
        boxMean = boxMean,
        innerf = innerf,
        outerf = outerf)

    analysis <- ordSummaryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

